"""switch to core

Revision ID: adb787043f00
Revises: e904622bf93c
Create Date: 2026-08-03 15:25:24.269948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adb787043f00'
down_revision: Union[str, Sequence[str], None] = 'e904622bf93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('destinations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('destinations', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('destinations', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('destinations', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('destinations', 'embedding',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('destinations', 'embedding',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('destinations', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('destinations', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('destinations', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('destinations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
